<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div id="wrapper">
	<?php
	include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/nav.phtml");
	?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $view['user']['name'];?> 每日工作表</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
			<?php
			include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_count_module.phtml");
			?>
            <div class="row">
                <div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							每日工作表
						</div>
						<div class="panel-body">
							<div class="dataTable_wrapper">
								<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
									<div class="row">
										<div class="col-sm-12">
											<table class="table table-striped table-bordered table-hover dataTable no-footer">
													<?php
													switch ($view['action']) {
														case 'write':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/dailywork_write.phtml");
														break;
														default:
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/dailywork_list.phtml");
													}
													?>
											</table>
										</div>
										<div style="float:right"><?php echo $view['pagination'];?></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
        <!-- /#page-wrapper -->
    </div>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.btn-default').click(function() {
			var data = {};
			data['code'] = $('select[name=code]').val();
			$('input.form-control').each(function(k, v) {
				data[v.name] = v.value;
			});
			var work_id = $('input[name=work_id]').val();
			if (work_id) {
				data['work_id'] = work_id;
				gateway = '/dailywork/modify/';
			} else {
				gateway = '/dailywork/create/';
			}
			$.post(gateway, data, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
		$('.btn-danger').click(function() {
			$.get('/dailywork/delete/', {work_id : $(this).attr('ref')}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
		$('input[name=date]').datepicker({format: 'yyyy-mm-dd'});
	});
	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
