<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div id="wrapper">
	<?php
	include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/nav.phtml");
	?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">每日工作表</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
			<?php
			include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_count_module.phtml");
			?>
            <div class="row">
                <div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							每日工作表
						</div>
						<div class="panel-body">
							<div class="dataTable_wrapper">
								<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
									<div class="row">
										<div class="col-sm-12">
											<table class="table table-striped table-bordered table-hover dataTable no-footer">
												<thead>
													<tr>
														<th>项目代号</th>
														<th>工作内容</th>
														<th>完成情况</th>
														<th>工时</th>
														<th>问题描述和下一步计划</th>
													</tr>
												</thead>
												<tbody>
													<?php
													switch ($view['action']) {
														case 'write':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/dailywork_write.phtml");
														break;
														default:
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/dailywork_list.phtml");
													}
													?>
												</tbody>
											</table>
										</div>
										<div style="float:right"><?php echo $view['pagination'];?></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
        <!-- /#page-wrapper -->
    </div>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.btn-default').click(function() {
			var data = {};
			data['code'] = $('select[name=code]').val();
			$('input.form-control').each(function(k, v) {
				data[v.name] = v.value;
			});
			$.post('/dailywork/create/', data, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
	});
	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
