													<?php
													foreach ($view['works'] as $w) {
													?>
													<tr>
														<td><?php echo $w['code'];?></td>
														<td><?php echo $w['content'];?></td>
														<td><?php echo $w['completion'];?></td>
														<td><?php echo $w['hours'];?></td>
														<td><?php echo $w['description'];?></td>
													</tr>
													<?php
													}
													?>
