<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div id="wrapper">
	<?php
	include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/nav.phtml");
	?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">部门管理</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-tasks fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">12</div>
                                    <div>您正在进行的项目有：</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.row -->
			
            <div class="row">
                <div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							部门列表
						</div>
						<div class="panel-body">
							<div class="dataTable_wrapper">
								<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
									<div class="row">
										<div class="col-sm-12">
											<table class="table table-striped table-bordered table-hover dataTable no-footer">
												<thead>
													<tr>
														<th>部门编号</th>
														<th>部门名称</th>
														<th>删除</th>
													</tr>
												</thead>
												<tbody>
													<?php
													foreach ($view['departments'] as $d) {
													?>
													<tr>
														<td><?php echo $d['id'];?></td>
														<td><?php echo $d['name'];?></td>
														<td><button ref="<?php echo $d['id'];?>" class="btn btn-danger" type="button">删除</button></td>
													</tr>
													<?php
													}
													?>
													<tr>
														<td><label>部门名称</label></td>
														<td><input class="form-control" name="name"/></td>
														<td><button class="btn btn-primary" type="button">添加</button></td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
	</div>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.btn-danger').click(function() {
			$.get('/department/delete/', {id : $(this).attr('ref')}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
		$('.btn-primary').click(function() {
			$.post('/department/create/', {name : $('input[name=name]').val()}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			});
		});
	});
	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
