												<thead>
													<tr>
														<td>项目编号</td>
														<td>成员编号</td>
														<td>姓名</td>
														<td>删除成员</td>
													</tr>
												</thead>
												<tbody>
												<?php
												foreach ($view['members'] as $user) {
												?>
													<tr>
														<td><?php echo $view['project']['code'];?></td>
														<td><?php echo $user['user_id'];?></td>
														<td><?php echo $user['name'];?></td>
														<td><button ref="<?php echo $user['user_id'];?>" class="btn btn-danger" type="button">删除</button></td>
													</tr>
												<?php
												}
												?>
												<tr>
													<td>添加成员</td>
													<td>
														<select class="form-control" name="user_id">
															<?php
															foreach ($view['users'] as $user) {
															?>
															<option value="<?php echo $user['user_id'];?>"><?php echo $user['name'];?></option>
															<?php
															}
															?>
														</select>
													</td>
													<td><button class="btn btn-primary" type="button">添加</button></td>
												</tr>
												</tbody>
