<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div id="wrapper">
	<?php
	include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/nav.phtml");
	?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">项目管理</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
			<?php
			include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_count_module.phtml");
			?>
            <div class="row">
                <div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							项目列表
						</div>
						<div class="panel-body">
							<div class="dataTable_wrapper">
								<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
									<div class="row">
										<div class="col-sm-12">
											<table class="table table-striped table-bordered table-hover dataTable no-footer">
													<?php
													switch ($view['action']) {
														case 'edit':
														case 'add':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_add.phtml");
														break;
														case 'view_member':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_view_member.phtml");
														break;
														case 'view_dailywork':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_view_dailywork.phtml");
														break;
														default:
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_list.phtml");
													}
													?>
											</table>
										</div>
										<div style="float:right"><?php echo $view['pagination'];?></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
	</div>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.btn-default').click(function() {
			var data = {};
			$('.form-control').each(function(k, v) {
				data[v.name] = v.value;
			});
			var gateway = data['id'] != '' ? '/project/modify/' : '/project/create/';
			$.post(gateway, data, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
		$('input[name=start]').datepicker({format: 'yyyy-mm-dd'});
		$('input[name=finish]').datepicker({format: 'yyyy-mm-dd'});
		$('.btn-danger').click(function() {
			$.get('/project/delete/', {id : $(this).attr('ref')}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
	});

	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
