												<thead>
													<tr>
														<td>项目编号</td>
														<td>成员编号</td>
														<td>姓名</td>
														<td>删除成员</td>
													</tr>
												</thead>
												<tbody>
												<?php
												foreach ($view['members'] as $user) {
												?>
													<tr>
														<td><?php echo $view['project']['code'];?></td>
														<td><?php echo $user['user_id'];?></td>
														<td><?php echo $user['name'];?></td>
														<?php
														if ($user['user_id'] == $view['project']['manager_id']) {
														?>
														<td>负责人</td>
														<?php
														} else {
														?>
														<td><button ref="<?php echo $user['user_id'];?>" class="btn btn-danger" type="button">删除</button></td>
														<?php
														}
														?>
													</tr>
												<?php
												}
												if ($view['users']) {
												?>
												<tr>
													<td>添加成员</td>
													<td>
														<select class="form-control" name="user_id">
															<?php
															foreach ($view['users'] as $user) {
															?>
															<option value="<?php echo $user['user_id'];?>"><?php echo $user['name'];?></option>
															<?php
															}
															?>
														</select>
													</td>
													<td><button class="btn btn-primary" type="button">添加</button></td>
												</tr>
												<?php
												}
												?>
												</tbody>
												<script type="text/javascript">
												$('.btn-primary').click(function() {
													var user_id = $('select[name=user_id]').val();
													$.post('/project/member/p/<?php echo $view['project']['project_id'];?>/add/', {u : user_id}, function(data) {
														if (data['success'] == true) {
															window.location.reload();
														}
													}, 'json');
												});

												$('.btn-danger').click(function() {
													var user_id = $(this).attr('ref');
													$.post('/project/member/p/<?php echo $view['project']['project_id'];?>/delete/', {u : user_id}, function(data) {
														if (data['success'] == true) {
															window.location.reload();
														}
													}, 'json');
												});
												</script>
