<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div id="wrapper">
	<?php
	include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/nav.phtml");
	?>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">用户管理</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
			<?php
			include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/project_count_module.phtml");
			?>
            <div class="row">
                <div class="col-lg-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							用户列表
						</div>
						<div class="panel-body">
							<div class="dataTable_wrapper">
								<div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
									<div class="row">
										<div class="col-sm-12">
											<table class="table table-striped table-bordered table-hover dataTable no-footer">
													<?php
													switch ($view['action']) {
														case 'edit':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/user_edit.phtml");
														break;
														case 'add':
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/user_add.phtml");
														break;
														default:
														include("{$_SERVER['DOCUMENT_ROOT']}/../html/pms/user_list.phtml");
													}
													?>
											</table>
										</div>
										<div style="float:right"><?php echo $view['pagination'];?></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
	</div>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.btn-default').click(function() {
			var data = {};
			$('.form-control').each(function(k, v) {
				data[v.name] = v.value;
			});
			var p = $('p[name=user_id]');
			var gateway;
			if (p.html()) {
				data['user_id'] = p.html();
				gateway = '/user/modify/';
			} else {
				gateway = '/user/create/';
			}
			$.post(gateway, data, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
		$('.btn-danger').click(function() {
			$.get('/user/delete/', {user_id : $(this).attr('ref')}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
	});
	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
