												<thead>
													<tr>
														<th>姓名</th>
														<th>邮箱</th>
														<th>密码</th>
														<th>部门</th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td><input name="name" class="form-control"/></td>
														<td><input name="email" class="form-control" style="width:250px;"/></td>
														<td><input type="password" name="password" class="form-control" /></td>
														<td>
															<select name="department" class="form-control">
																<?php
																foreach ($view['departments'] as $d) {
																?>
																<option value="<?php echo $d['id'];?>"><?php echo $d['name'];?></option>
																<?php
																}
																?>
															</select>
														</td>
													</tr>
													<tr>
														<td colspan="5"><button class="btn btn-default" type="submit">提交</button></td>
													</tr>
												</tbody>
