
    <!-- Bootstrap Core JavaScript -->
    <script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/static/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/dist/js/sb-admin-2.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
		$('.sign-out').click(function() {
			$.get('/login/signout/', {}, function(data) {
				if (data['success']) {
					window.location.href = data['uri'];
				}
			});
		});
	});
	</script>
</body>

</html>
