<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/header.phtml");
?>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <a href="javascript:void(0);" class="btn btn-lg btn-success btn-block">Login</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<script type="text/javascript">
	jQuery(document).ready(function() {
		$('.btn-lg').click(function() {
			var email = $('input[name=email]').val();
			var password = $('input[name=password]').val();
			var remember = $('input[name=remember]').is(':checked');
			$.post('/login/sign/', {email : email, password : password, remember : remember}, function(data) {
				if (data['success'] == true) {
					window.location.href = data['uri'];
				}
			}, 'json');
		});
	});
	</script>
<?php
include("{$_SERVER['DOCUMENT_ROOT']}/../html/footer.phtml");
?>
